apiVersion: v1
kind: Secret
metadata:
  name: task-platform-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: taskpass
  JWT_SECRET: i-am-keeping-this-in-a-real-environment
