apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-platform

resources:
  - ../../base

images:
  - name: task-platform/backend
    newTag: dev

  - name: task-platform/frontend
    newTag: dev

patches:
  - target:
      version: v1
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      version: v1
      kind: Deployment
      name: worker
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      version: v1
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      version: v1
      kind: Deployment
      name: nginx
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      group: autoscaling
      version: v2
      kind: HorizontalPodAutoscaler
      name: backend
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1

  - target:
      group: autoscaling
      version: v2
      kind: HorizontalPodAutoscaler
      name: worker
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1